### ISSUE TITLE
Проверка лабораторных

### ISSUE THREAD

**Issue by NataliaSafiullina** [5P453C0VV80Y/informationSystemsTools#2]
**Лаб 1** 
Всё сделано, зачтено полностью.

**Лаб 2**
Задание 4.
Тут: 3**39 - int(float(3**39))
Получается разность равная 11. При преобразовании типов мы потеряли 11, из-за разного хранения различных типов данных. 

Задание 6.
Ответ не точный. Доктор ещё едет обратно, а нам нужно общее время на дорогу.

Задание 13.
Результат выводится в строчку, не очень удобно читать таблицу умножения.

Задание 14.
Бесконечный цикл получился. Проверьте, введите 5 или 6. 

Все остальные задачи сделаны правильно.

**Лаб 3**
Всё правильно! Я никогда не пробовала образ MongoDB Community Server, посмотрим, что у вас с ним получится.

**Лаб 4**
Задание 4.
Не совсем точно. Нужно было "количество подтверждений присоединения к группам".
У вас просто количество user_id.

Задание 12.
В задании не говорится про среднее значение кармы, нужна сумма кармы.
В вашем запросе, считается среднее значение.

Задание 13
Использовали:
expireat index 120
В отличие от expire задает время жизни ключа от начала времен Unix, т.е. от 1-го января 1970. Если задать прошлое, т.е. указать 120 секунд, то ключ тут же уничтожиться. Видите у вас на скриншоте persist index вернул 0 (команда не выполнена), потому ключа index уже нет. 

Задание 14
Задание 14 сделано не правильно. Redis сообщал вам, что не понял и не выполнил команды, это когда ответ приходит: (integer) 0.

Задание 15
Команды написаны правильно, но на скриншотах не правильно.

**Лаб 5**
Задание 2.
Ошибка, смотрите прикрепленный файл. Предлагаю подумать в чем ошибка.

![2024-01-07 14_01_17-Proverka – main py](https://github.com/5P453C0VV80Y/informationSystemsTools/assets/112258208/e260c595-0995-45f7-9a19-cd84a0daafc4)

Задание 3.
Работает правильно. Но не очень красиво записывать в список в первый элемент весь список слов, создавая при этом список списков, в двумерном списке здесь нет надобности, создает проблемы в чтении кода. 

Задание 1, 4 - правильно.

У вас идентичный код с Игорем Гореловым. 

**Лаб 6**
Прочитала, что с графиком не разобрались. Если интересно, разберёмся на занятиях.
А так за эту работу 4 баллов из 8 за аккуратные формулы.
Цель, конечно, этого всего - наглядный график выгорания задач.

**Лаб 7**
Бота проверила, код работает. :)
Напомню, что в Django надо было добавить что-то своё. Покажите на занятиях.

**Лаб 8**
Всё верно!

Итого: 58 баллов из 75

**Comment by 5P453C0VV80Y** [comment]
добрый вечер
два вопроса есть
58 баллов это какая-то оценка за лабы? если да, то какая
и нужно ли вносить какие-то правки, или уже итак все понятно, и надо будет просто добавить в 7 лабе что-то свое?

**Comment by NataliaSafiullina** [comment]
Добрый день!
Баллы больше 51 - это три балла. Если хотите 4 или 5 на экзамене, лучше доделать задания (можно не все), чтобы подстраховать себя. На 4 или 5 надо будет ответить устно на вопросы билета.

**Comment by 5P453C0VV80Y** [comment]
и вновь приветствую
по баллам ситуацию понял, нашел немного времени на фиксы
+ это исправленные, - нетронутые

**лаб 2------------------------------------------**
зад.4   - [+]
зад.6   - [+]
зад.13 - [-]
зад.14 - [-]

насчет шестого задания.. перечитал формулировку задания раз 5, но так и не смог увидеть, где там про возвращение... тем не менее, вроде как, дополнил код корректно

**лаб 4------------------------------------------**
зад.4   - [-]
зад.12 - [+]
зад.13 - [+]
зад.14 - [+]
зад.15 - [+ (?)]

задание 12...
упс :)
задание 13
прислушался к Вам, убрал 'at'.. как-то по тупому вышло поставить timeToLive🥇  
задание 15
не совсем понял, что не так на скриншотах
справа кусочек cmd, слева консоль vscode. в vscode слушаю, в cmd отправляю и вижу в vscode сообщение...

**лаб 5------------------------------------------**
зад.2 - [+]
вроде починил.. а причина в типизации, вероятнее всего по дефолту в пайтон стоит строка в массивах. можно было бы создать массив с импортом * и указать ключ i, типа... numbers = ('i',['вот тут массив через запятые']).. хотя это же минусы..

**лаб 7------------------------------------------**
[+]
по условиям задачи "код должен отличаться" от Вашего, я добавил смешного кота
![showcase](https://github.com/5P453C0VV80Y/informationSystemsTools/assets/101409523/499ff9eb-541b-4003-9d21-96ee6f34adc8)

**Comment by NataliaSafiullina** [comment]
Лаб 2 - стало 7 из 8

Лаб 4 - 12+, 13+, 14 - не нужно было перерывать всю спецификацию Redis, всё это было написано тут же в тексте лабораторной работы, ну и, я как-то же нашла :), 15+. Стало 14 из 15.

Лаб 5 - да, всё введённое через input становится строками. Стало 8 из 8.

Лаб 7 - кот то есть :), а вот форма, которая выше кота, сломалась. 

Итого 65 из 75.

**Comment by 5P453C0VV80Y** [comment]
нет нет, с формой все в порядке
просто не было времени запускать venv и я быстренько закинул .html в браузер для скриншота!!!
